buildscript {
    def agpVersion = project.findProperty("androidGradlePluginVersion") ?: "8.4.2"
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:${agpVersion}"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }

    configurations.configureEach {
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
    }
}
