apply plugin: 'com.android.application'

android {
    namespace 'eu.pryds.ve'
    compileSdk 34

    defaultConfig {
        applicationId "eu.pryds.ve"
        minSdk 14
        targetSdk 34
        versionCode 9
        versionName "0.1.5"
    }

    sourceSets {
        main {
            manifest.srcFile '../AndroidManifest.xml'
            java.srcDirs = ['../src']
            res.srcDirs = ['../res']
            assets.srcDirs = ['../assets']
            jniLibs.srcDirs = ['../libs']
            aidl.srcDirs = ['../src']
        }
    }

    buildFeatures {
        aidl true
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), '../proguard-project.txt'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation fileTree(dir: '../libs', include: ['*.jar'])
    implementation 'androidx.activity:activity:1.9.3'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.fragment:fragment:1.8.2'
    implementation 'androidx.preference:preference:1.2.1'
}
